# Generated lexer - do not edit manually
# This file was generated by YALex lexer generator
import sys

# --- DFA Transition Table ---
_TRANSITIONS = {
    0: {'\t': 3, '\n': 3, ' ': 3, '(': 6, ')': 8, '*': 7, '+': 1, '-': 4, '/': 5, '0': 2, '1': 2, '2': 2, '3': 2, '4': 2, '5': 2, '6': 2, '7': 2, '8': 2, '9': 2},
    2: {'0': 2, '1': 2, '2': 2, '3': 2, '4': 2, '5': 2, '6': 2, '7': 2, '8': 2, '9': 2},
    3: {'\t': 3, '\n': 3, ' ': 3},
}

_START_STATE = 0

_ACCEPT = {
    1: 2,  # priority 2
    2: 1,  # priority 1
    3: 0,  # priority 0
    4: 3,  # priority 3
    5: 5,  # priority 5
    6: 6,  # priority 6
    7: 4,  # priority 4
    8: 7,  # priority 7
}

def _execute_action(action_id, lexeme):
    lxm = lexeme  # alias for use in actions
    if action_id == 0:
        return None
    elif action_id == 1:
        return ("NUMBER", lxm)
    elif action_id == 2:
        return ("PLUS", lxm)
    elif action_id == 3:
        return ("MINUS", lxm)
    elif action_id == 4:
        return ("TIMES", lxm)
    elif action_id == 5:
        return ("DIV", lxm)
    elif action_id == 6:
        return ("LPAREN", lxm)
    elif action_id == 7:
        return ("RPAREN", lxm)
    return None

def tokenize(text):
    """Tokenize input text using the generated DFA."""
    pos = 0
    line = 1
    col = 1
    tokens = []
    errors = []
    while pos < len(text):
        state = _START_STATE
        last_accept = None
        last_accept_pos = pos
        current = pos
        while current < len(text):
            ch = text[current]
            if state in _TRANSITIONS and ch in _TRANSITIONS[state]:
                state = _TRANSITIONS[state][ch]
                current += 1
                if state in _ACCEPT:
                    last_accept = _ACCEPT[state]
                    last_accept_pos = current
            else:
                break
        if last_accept is not None:
            lexeme = text[pos:last_accept_pos]
            lxm = lexeme  # alias used in actions
            result = _execute_action(last_accept, lexeme)
            if result is not None:
                tokens.append(result)
            for ch in lexeme:
                if ch == '\n':
                    line += 1
                    col = 1
                else:
                    col += 1
            pos = last_accept_pos
        else:
            error_msg = f'Lexical error at line {line}, col {col}: unexpected character {text[pos]!r}'
            errors.append(error_msg)
            print(error_msg, file=sys.stderr)
            if text[pos] == '\n':
                line += 1
                col = 1
            else:
                col += 1
            pos += 1
    return tokens, errors

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python <lexer>.py <input_file>", file=sys.stderr)
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        text = f.read()
    tokens, errors = tokenize(text)
    for token in tokens:
        print(token)
    if errors:
        print(f"\n{len(errors)} lexical error(s) found.", file=sys.stderr)
