from automata.models import DFA
from yalex.models import YAlexSpec, PatternAction


def generate_lexer(dfa: DFA, spec: YAlexSpec, patterns: list[PatternAction],
                   output_path: str):
    """Generate a standalone Python lexer file from a minimized DFA.

    The generated file is completely independent — it contains the DFA
    transition table, accept states, action code, and a tokenize() function.
    """
    lines = []
    lines.append("# Generated lexer - do not edit manually")
    lines.append("# This file was generated by YALex lexer generator")
    lines.append("import sys")
    lines.append("")

    # Header
    if spec.header:
        lines.append("# --- Header ---")
        lines.append(spec.header)
        lines.append("")

    # DFA transition table
    lines.append("# --- DFA Transition Table ---")
    lines.append("_TRANSITIONS = {")
    for state_id in sorted(dfa.transitions.keys()):
        trans = dfa.transitions[state_id]
        if trans:
            trans_repr = "{"
            items = []
            for symbol in sorted(trans.keys()):
                target = trans[symbol]
                items.append(f"{symbol!r}: {target}")
            trans_repr += ", ".join(items)
            trans_repr += "}"
            lines.append(f"    {state_id}: {trans_repr},")
    lines.append("}")
    lines.append("")

    lines.append(f"_START_STATE = {dfa.start}")
    lines.append("")

    # Accept states with action indices
    # Map each unique action to an index
    action_map = {}  # action_code -> index
    for pattern in patterns:
        if pattern.action is not None and pattern.action not in action_map:
            action_map[pattern.action] = len(action_map)

    lines.append("_ACCEPT = {")
    for state_id in sorted(dfa.accept_states.keys()):
        action_code, priority = dfa.accept_states[state_id]
        if action_code in action_map:
            lines.append(f"    {state_id}: {action_map[action_code]},  # priority {priority}")
    lines.append("}")
    lines.append("")

    # Action functions
    lines.append("def _execute_action(action_id, lexeme):")
    lines.append("    lxm = lexeme  # alias for use in actions")
    if action_map:
        first = True
        for action_code, idx in action_map.items():
            keyword = "if" if first else "elif"
            lines.append(f"    {keyword} action_id == {idx}:")
            # Indent each line of the action code
            action_lines = action_code.strip().split('\n')
            for al in action_lines:
                al_stripped = al.strip()
                if al_stripped:
                    lines.append(f"        {al_stripped}")
            first = False
    else:
        lines.append("    pass")
    lines.append("    return None")
    lines.append("")

    # Tokenize function
    lines.append("def tokenize(text):")
    lines.append('    """Tokenize input text using the generated DFA."""')
    lines.append("    pos = 0")
    lines.append("    line = 1")
    lines.append("    col = 1")
    lines.append("    tokens = []")
    lines.append("    errors = []")
    lines.append("    while pos < len(text):")
    lines.append("        state = _START_STATE")
    lines.append("        last_accept = None")
    lines.append("        last_accept_pos = pos")
    lines.append("        current = pos")
    lines.append("        while current < len(text):")
    lines.append("            ch = text[current]")
    lines.append("            if state in _TRANSITIONS and ch in _TRANSITIONS[state]:")
    lines.append("                state = _TRANSITIONS[state][ch]")
    lines.append("                current += 1")
    lines.append("                if state in _ACCEPT:")
    lines.append("                    last_accept = _ACCEPT[state]")
    lines.append("                    last_accept_pos = current")
    lines.append("            else:")
    lines.append("                break")
    lines.append("        if last_accept is not None:")
    lines.append("            lexeme = text[pos:last_accept_pos]")
    lines.append("            lxm = lexeme  # alias used in actions")
    lines.append("            result = _execute_action(last_accept, lexeme)")
    lines.append("            if result is not None:")
    lines.append("                tokens.append(result)")
    lines.append("            for ch in lexeme:")
    lines.append("                if ch == '\\n':")
    lines.append("                    line += 1")
    lines.append("                    col = 1")
    lines.append("                else:")
    lines.append("                    col += 1")
    lines.append("            pos = last_accept_pos")
    lines.append("        else:")
    lines.append("            error_msg = f'Lexical error at line {line}, col {col}: unexpected character {text[pos]!r}'")
    lines.append("            errors.append(error_msg)")
    lines.append("            print(error_msg, file=sys.stderr)")
    lines.append("            if text[pos] == '\\n':")
    lines.append("                line += 1")
    lines.append("                col = 1")
    lines.append("            else:")
    lines.append("                col += 1")
    lines.append("            pos += 1")
    lines.append("    return tokens, errors")
    lines.append("")

    # Trailer
    if spec.trailer:
        lines.append("# --- Trailer ---")
        lines.append(spec.trailer)
        lines.append("")

    # Main block
    lines.append('if __name__ == "__main__":')
    lines.append("    if len(sys.argv) < 2:")
    lines.append('        print("Usage: python <lexer>.py <input_file>", file=sys.stderr)')
    lines.append("        sys.exit(1)")
    lines.append('    with open(sys.argv[1], "r", encoding="utf-8") as f:')
    lines.append("        text = f.read()")
    lines.append("    tokens, errors = tokenize(text)")
    lines.append("    for token in tokens:")
    lines.append("        print(token)")
    lines.append("    if errors:")
    lines.append(f'        print(f"\\n{{len(errors)}} lexical error(s) found.", file=sys.stderr)')
    lines.append("")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    return output_path
